name: Backfill Docker Images

on:
  workflow_dispatch:
    inputs:
      strapi_versions:
        description: 'Comma-separated list of Strapi versions to backfill (e.g., 4.15.0 or 4.15.0,4.15.1,5.0.0)'
        required: true

jobs:
  prepare-versions:
    runs-on: ubuntu-latest
    outputs:
      versions: ${{ steps.set-versions.outputs.versions }}
      highest_v4: ${{ steps.set-versions.outputs.highest_v4 }}
      highest_v5: ${{ steps.set-versions.outputs.highest_v5 }}
    steps:
      - id: set-versions
        run: |
          # Convert comma-separated string to JSON array and clean whitespace
          VERSIONS=$(echo '${{ inputs.strapi_versions }}' | jq -R -s -c 'split(",") | map(select(length > 0) | gsub("^\\s+|\\s+$"; ""))')
          # Find highest versions for v4 and v5
          HIGHEST_V4=$(echo $VERSIONS | jq -r 'map(select(startswith("4"))) | sort_by(split(".") | map(tonumber)) | last')
          HIGHEST_V5=$(echo $VERSIONS | jq -r 'map(select(startswith("5"))) | sort_by(split(".") | map(tonumber)) | last')
          echo "versions=${VERSIONS}" >> "$GITHUB_OUTPUT"
          echo "highest_v4=${HIGHEST_V4}" >> "$GITHUB_OUTPUT"
          echo "highest_v5=${HIGHEST_V5}" >> "$GITHUB_OUTPUT"

  test-image:
    name: Test Debian Image
    needs: [prepare-versions]
    runs-on: ubuntu-latest

    env:
      TAG: ${{ matrix.version }}
      POSTGRES_HOST: 172.17.0.1
      MYSQL_HOST: 172.17.0.1

    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-versions.outputs.versions) }}
        upgrade-path:
          - version: '4'
            old_version: 4.15.0
          - version: '5'
            old_version: 5.0.0
      
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: strapi
          POSTGRES_PASSWORD: strapi
          POSTGRES_DB: strapi
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      mysql:
        image: bitnami/mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: strapi
          MYSQL_USER: strapi
          MYSQL_PASSWORD: strapi
          MYSQL_DATABASE: strapi
          MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        ports:
          - 3306:3306
    
    steps:
      - name: Get Current Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build Latest v${{ matrix.upgrade-path.version }} Strapi Image and Export to Docker
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./images/strapi-debian
          build-args: |
            STRAPI_VERSION=${{ env.TAG }}
            NODE_VERSION=20
            NODE=node
            GITHUB_ACTIONS=1
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:latest

      - name: Test Latest v${{ matrix.upgrade-path.version }} Strapi Image with SQLite
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        timeout-minutes: 10
        run: |
          docker run --rm ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:latest

      - name: Test Latest v${{ matrix.upgrade-path.version }} Strapi Image with PostgreSQL
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        timeout-minutes: 10
        run: |
          docker run --rm \
            -e DATABASE_CLIENT=postgres \
            -e DATABASE_HOST=${{ env.POSTGRES_HOST }} \
            -e DATABASE_PORT=5432 \
            -e DATABASE_NAME=strapi \
            -e DATABASE_USERNAME=strapi \
            -e DATABASE_PASSWORD=strapi \
            ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:latest
      
      - name: Test Latest v${{ matrix.upgrade-path.version }} Strapi Image with MySQL
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        timeout-minutes: 10
        run: |
          docker run --rm \
            -e DATABASE_CLIENT=mysql \
            -e DATABASE_HOST=${{ env.MYSQL_HOST }} \
            -e DATABASE_PORT=3306 \
            -e DATABASE_NAME=strapi \
            -e DATABASE_USERNAME=strapi \
            -e DATABASE_PASSWORD=strapi \
            ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:latest
      
      - name: Create Temp Volume
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        run: |
          mkdir ${{ runner.temp }}/strapi-${{ matrix.upgrade-path.version }}-${{ github.run_id }}
      
      - name: Build Old v${{ matrix.upgrade-path.version }} Strapi Image and Export to Docker
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        uses: docker/build-push-action@v6
        with:
          load: true
          context: ./images/strapi-debian
          build-args: |
            STRAPI_VERSION=${{ matrix.upgrade-path.old_version }}
            NODE_VERSION=20
            NODE=node
            GITHUB_ACTIONS=1
          tags: ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:old

      - name: Init Old v${{ matrix.upgrade-path.version }} Strapi Image with SQLite
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        timeout-minutes: 10
        run: |
          docker run --rm -v ${{ runner.temp }}/strapi-${{ matrix.upgrade-path.version }}-${{ github.run_id }}:/srv/app ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:old
        
      - name: Test Upgrade from v${{ matrix.upgrade-path.version }} to Latest Strapi Image with SQLite
        if: ${{ matrix.upgrade-path.version == '4' || (matrix.upgrade-path.version == '5' && startsWith(matrix.version, '5')) }}
        timeout-minutes: 10
        run: |
          docker run --rm -v ${{ runner.temp }}/strapi-${{ matrix.upgrade-path.version }}-${{ github.run_id }}:/srv/app ${{ secrets.DOCKER_USERNAME }}/strapi-${{ matrix.upgrade-path.version }}:latest

  build-and-push:
    name: Build and Push Images
    needs: [prepare-versions, test-image]
    runs-on: ubuntu-latest

    env:
      TAG: ${{ matrix.version }}

    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-versions.outputs.versions) }}
        os: [debian, alpine]
        arch:
          - platform: linux/amd64
            node: node
          - platform: linux/arm64
            node: arm64v8/node

    steps:
      - name: Get Current Repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}  

      - name: Set LATEST env
        run: |
          if [[ "${{ matrix.version }}" == 5* ]]; then
            if [[ "${{ matrix.version }}" == "${{ needs.prepare-versions.outputs.highest_v5 }}" ]]; then
              echo "LATEST=latest" >> $GITHUB_ENV
            else
              echo "LATEST=skip-latest" >> $GITHUB_ENV
            fi
          elif [[ "${{ matrix.version }}" == 4* ]]; then
            if [[ "${{ matrix.version }}" == "${{ needs.prepare-versions.outputs.highest_v4 }}" ]]; then
              echo "LATEST=latest-v4" >> $GITHUB_ENV
            else
              echo "LATEST=skip-latest" >> $GITHUB_ENV
            fi
          fi

      - name: Build and Push ${{ matrix.os }} (${{ matrix.arch.platform }})
        uses: docker/build-push-action@v6
        with:
          context: ./images/strapi-${{ matrix.os }}
          platforms: ${{ matrix.arch.platform }}
          build-args: |
            STRAPI_VERSION=${{ env.TAG }}
            NODE_VERSION=20
            NODE=${{ matrix.arch.node }}
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/strapi:${{ env.TAG }}${{ matrix.os == 'alpine' && '-alpine' || '' }}${{ matrix.arch.platform == 'linux/arm64' && '-arm64' || '' }}
            ${{ env.LATEST != 'skip-latest' && format('{0}/strapi:{1}{2}{3}', secrets.DOCKER_USERNAME, env.LATEST, matrix.os == 'alpine' && '-alpine' || '', matrix.arch.platform == 'linux/arm64' && '-arm64' || '') || '' }}

  release:
    name: Release
    needs: [prepare-versions, build-and-push]
    runs-on: ubuntu-latest

    env:
      TAG: ${{ matrix.version }}

    permissions:
      contents: write

    strategy:
      matrix:
        version: ${{ fromJson(needs.prepare-versions.outputs.versions) }}

    steps:
      - name: Get Current Repository
        uses: actions/checkout@v4

      - name: Create Release in GitHub
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag_name: v${{ env.TAG }}
          prerelease: false
          draft: false
          generate_release_notes: true
          name: Release ${{ env.TAG }}
          body: Strapi v${{ env.TAG }}
          make_latest: ${{ matrix.version == needs.prepare-versions.outputs.highest_v5 }}
