###################
# ENV VARS:
# - PAT (generated at Personal Access Tokens - with workflow access checked)
###################

name: Create new release manually

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'version'
        required: true
        default: '4.25.0'
        type: string

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}

      - name: Fetch v4 release version
        id: fetch-v4-version
        if: startsWith(github.event.inputs.version, '4')
        run: |
          echo "${{ github.event.inputs.version }}" > release-versions/strapi-v4-latest.txt
      
      - name: Fetch v5 release version
        id: fetch-v5-version
        if: startsWith(github.event.inputs.version, '5')
        run: |
          echo "${{ github.event.inputs.version }}" > release-versions/strapi-v5-latest.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: New manual release ${{ github.event.inputs.version }}
